### ISSUE TITLE
types are not recognized as constructors

### ISSUE THREAD

**Issue by mrgnhnt96** [mrgnhnt96/Hive_Object_Converter#2]
List<Map<String, int>> breakfast;
  List<Map<String, int>> entree;
  List<Map<String, int>> snacks;
  List<Map<String, int>> treats;

these were missed and need to be field types

**Comment by Manuelbaun** [comment]
I have created a pull request and have addressed it in my fork too, please have a look. As far as I can tell, I fixed it.

**Comment by mrgnhnt96** [comment]
This has been fixed, thanks!
